[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mpl_core_anchor_wrapper = "2CTGnypSjA6gYxwhKxb1HVhMuaGx5QCe4qGvzsF5Kqtt"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/programs/mpl_core.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
